### ISSUE TITLE
Use 'ICE candidates' instead of 'candidate addresses' (Editorial)

### ISSUE THREAD

**Issue by cdh4u** [ice-wg/draft-ice-pac#4]
Where: Introduction

What: s/candidate addresses/ICE candidates

Why: An address is just one part of a candidate

**Comment by juberti** [comment]
I tend to think this is implicit, and won't confuse anyone.

**Comment by cdh4u** [comment]
We use "candidates" everywhere else, and it is not only the addresses that are exchanged.

**Comment by juberti** [comment]
8445 also uses 'candidate transport addresses' in Section 2. But open to some other text here, 'ICE candidates' feels like it doesn't explain enough to the reader.

**Comment by cdh4u** [comment]
> 8445 also uses 'candidate transport addresses' in Section 2. But open to some other text here, 'ICE 
> candidates' feels like it doesn't explain enough to the reader.

The paragraph says:

"Typically, when using ICE, endpoints will exchange candidate addresses,
form a list of candidate pairs, and then test each candidate pair to see
if connectivity can be established. If the test for a given pair fails,
it is marked accordingly, and if all pairs have failed, the overall
ICE process is considered to have failed."

If people don't understand what an "ICE candidate" is they won't understand the rest of the text either :)

My point is that endpoints are *exchanging* candidates. The candidate transport addresses are then used for *sending* connectivity checks. So, if you want to include it, perhaps something like:

"and then test each candidate pair, by sending connectivity checks using the candidate transport addresses, to see if...."

**Comment by cdh4u** [comment]
Implemented in #13
