### ISSUE TITLE
Use 'connectivity' instead of 'peer-to-peer connection' (Editorial)

### ISSUE THREAD

**Issue by cdh4u** [ice-wg/draft-ice-pac#5]
Where: Abstract

What: s/peer-to-peer connection/connectivity

Why: We talk about establishing connectivity elsewhere

**Comment by juberti** [comment]
peer-to-peer seems important to retain here, not sure I agree with this change

**Comment by cdh4u** [comment]
Then we could at least use "peer-to-peer connectivity", because that seems to be used once in the Introduction of 8445.

**Comment by juberti** [comment]
I can get behind that.

**Comment by cdh4u** [comment]
Something happened. I forked the ICE WG repo, but when I created the PR it ended up in my private repo.

**Comment by juberti** [comment]
You used the wrong repo for the base repo. I fixed it in https://github.com/ice-wg/draft-ice-pac/pull/10.

**Comment by juberti** [comment]
I think I understand why that happened, ice-wg still thinks cdh4u is upstream, need to think about how to fix that.

**Comment by cdh4u** [comment]
Shouldn't it be possible to create a pull request to a fork?

I guess my repo isn't needed anymore, so in worse case we can just remove it.

**Comment by cdh4u** [comment]
Fixed in #10
