### ISSUE TITLE
ICE process failure clarification (Editorial/Technical)

### ISSUE THREAD

**Issue by cdh4u** [ice-wg/draft-ice-pac#6]
Where: Introduction 

What:

Replace:

"If the test for a given pair fails, it is marked accordingly, and if all pairs have failed, the overall
ICE process is considered to have failed."

...with something like:

"If the test for a given pair fails, it is marked accordingly, and if all pairs have failed, the associated checklist is considered to have failed. Once one or more checklists have failed, the ICE agent might consider the ICE process to have failed." 

WHY: The text is misleading, as an ICE agent can declare failure before all pairs have been checked, e.g., if a checklist associated with a stream that is required for the session has failed.

**Comment by juberti** [comment]
ok

**Comment by cdh4u** [comment]
Implemented in #12
