### ISSUE TITLE
Clarify that no candidate needs to be sent or received before starting timer (Technical)

### ISSUE THREAD

**Issue by cdh4u** [ice-wg/draft-ice-pac#7]
WHERE: Update to RFC 8445

WHAT:

Modify...

"; note that receipt of an ICE candidate is not required."

...so that it also indicates that no candidate needs to be SENT before the timer is started.

WHY: The text in unclear on whether a candidate needs to be sent or not before the timer is started. The text only says that a candidate does not need to be received.

**Comment by juberti** [comment]
ok

**Comment by cdh4u** [comment]
Implemented in #14
