### ISSUE TITLE
Is it clear enough that the timer will be used even if all remote candidates are discarded?

### ISSUE THREAD

**Issue by cdh4u** [ice-wg/draft-ice-pac#8]
When I read the "Relevant Scenarios", there are use-cases where an agent will not be able to create any pairs, as it may e.g., discard all remote candidates based on the IP address family they are associated with.

Do we think that the draft is clear that a timer will be started even if an agent will discard all candidates? Most of the text talks about not declaring failure when there are no more pairs to check, but it seems to assume that candidates have at least been accepted (otherwise they wouldn't be tested).

**Comment by juberti** [comment]
I tend to think so, since we say 'no pairs to check', say that receipt of a candidate isn't required, and explicitly mention this scenario.

**Comment by cdh4u** [comment]
Ok.
